name: Deploy to Alibaba Cloud

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 升级到最新版

      - name: Login to Alibaba Cloud Container Registry
        run: |
          echo "${{ secrets.ALIYUN_DOCKER_PASSWORD }}" | docker login --username ${{ secrets.ALIYUN_DOCKER_USERNAME }} --password-stdin crpi-nrc1eylr425ubrzn.cn-hangzhou.personal.cr.aliyuncs.com

      - name: Build Docker image
        run: docker build -t crpi-nrc1eylr425ubrzn.cn-hangzhou.personal.cr.aliyuncs.com/kakajun/nest-admin:latest .

      - name: Push Docker image
        run: docker push crpi-nrc1eylr425ubrzn.cn-hangzhou.personal.cr.aliyuncs.com/kakajun/nest-admin:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v1.0.3 # 升级到最新版
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            # 登录容器 registry
            echo "Logging into Alibaba Cloud Docker registry..."
            docker login --username ${{ secrets.ALIYUN_DOCKER_USERNAME }} --password ${{ secrets.ALIYUN_DOCKER_PASSWORD }} crpi-nrc1eylr425ubrzn.cn-hangzhou.personal.cr.aliyuncs.com

            # 停止并删除现有容器
            echo "Stopping and removing existing container..."
            docker rm -f nest-admin || true  # 强制删除，不存在则忽略

            # 拉取最新镜像
            echo "Pulling latest Docker image..."
            docker pull crpi-nrc1eylr425ubrzn.cn-hangzhou.personal.cr.aliyuncs.com/kakajun/nest-admin:latest

            # 确保宿主机配置目录存在，避免挂载为空
            echo "Preparing host config directory..."
            mkdir -p /root/nestconfig  # 确保宿主机有这个目录

            # 关键修复：如果宿主机配置目录为空，从镜像中复制默认配置
            if [ -z "$(ls -A /root/nestconfig)" ]; then
              echo "Copying default config from image to host..."
              # 运行临时容器，将镜像内的配置复制到宿主机目录
              docker run --rm -v /root/nestconfig:/host-config \
                crpi-nrc1eylr425ubrzn.cn-hangzhou.personal.cr.aliyuncs.com/kakajun/nest-admin:latest \
                sh -c "cp -r /app/dist/config/* /host-config/"
            fi

            # 启动新容器（使用宿主机的配置目录）
            echo "Starting new container..."
            docker run -d --name nest-admin \
              -v /root/nestconfig:/app/dist/config \  # 挂载宿主机配置目录
              -v /var/log/nginx:/var/log/nginx \
              -p 3001:3001 \
              -p 9551:80 \
              crpi-nrc1eylr425ubrzn.cn-hangzhou.personal.cr.aliyuncs.com/kakajun/nest-admin:latest

            echo "Deployment completed successfully."
